/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/candidates`; params?: Router.UnknownInputParams; } | { pathname: `/chat-room`; params?: Router.UnknownInputParams; } | { pathname: `/create-vacancy`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/legal`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/match`; params?: Router.UnknownInputParams; } | { pathname: `/rate`; params?: Router.UnknownInputParams; } | { pathname: `/register-employer`; params?: Router.UnknownInputParams; } | { pathname: `/register-worker`; params?: Router.UnknownInputParams; } | { pathname: `/user-profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/matches` | `/matches`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/saved` | `/saved`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/candidates`; params?: Router.UnknownOutputParams; } | { pathname: `/chat-room`; params?: Router.UnknownOutputParams; } | { pathname: `/create-vacancy`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/legal`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/match`; params?: Router.UnknownOutputParams; } | { pathname: `/rate`; params?: Router.UnknownOutputParams; } | { pathname: `/register-employer`; params?: Router.UnknownOutputParams; } | { pathname: `/register-worker`; params?: Router.UnknownOutputParams; } | { pathname: `/user-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/matches` | `/matches`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/saved` | `/saved`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/admin${`?${string}` | `#${string}` | ''}` | `/candidates${`?${string}` | `#${string}` | ''}` | `/chat-room${`?${string}` | `#${string}` | ''}` | `/create-vacancy${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/legal${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/match${`?${string}` | `#${string}` | ''}` | `/rate${`?${string}` | `#${string}` | ''}` | `/register-employer${`?${string}` | `#${string}` | ''}` | `/register-worker${`?${string}` | `#${string}` | ''}` | `/user-profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chats${`?${string}` | `#${string}` | ''}` | `/chats${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/matches${`?${string}` | `#${string}` | ''}` | `/matches${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/saved${`?${string}` | `#${string}` | ''}` | `/saved${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/candidates`; params?: Router.UnknownInputParams; } | { pathname: `/chat-room`; params?: Router.UnknownInputParams; } | { pathname: `/create-vacancy`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/legal`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/match`; params?: Router.UnknownInputParams; } | { pathname: `/rate`; params?: Router.UnknownInputParams; } | { pathname: `/register-employer`; params?: Router.UnknownInputParams; } | { pathname: `/register-worker`; params?: Router.UnknownInputParams; } | { pathname: `/user-profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/matches` | `/matches`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/saved` | `/saved`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
